CREATE TABLE product (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Product VARCHAR(255) NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Units VARCHAR(50) NOT NULL,
    Image VARCHAR(255) NOT NULL
);

CREATE TABLE orders (
    Order_ID INT AUTO_INCREMENT PRIMARY KEY,
    Client_Name VARCHAR(255) NOT NULL,
    Contact VARCHAR(20) NOT NULL,
    Product VARCHAR(255) NOT NULL,
    Quantity INT NOT NULL,
    Unit VARCHAR(50) NOT NULL,
    Total_Price DECIMAL(10,2) NOT NULL,
    Order_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);